# .github/workflows/firebase-deploy.yml

name: Deploy to Firebase Hosting

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main # Or your default branch (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest checkout action

      # 2. Install Firebase CLI
      #    Using a dedicated action is often cleaner than global npm install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 3. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          # Use the secret token you added to GitHub Secrets
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Deploy to Firebase Hosting.
          # The --only hosting flag ensures only hosting is deployed.
          # The --project flag explicitly targets your project (optional if .firebaserc is correct)
          firebase deploy --only hosting --project health-monitor-93518 --token "$FIREBASE_TOKEN" --non-interactive
